export default [
    {
      path:'/',
      name:'Layout',
      redirect:'/index',
      component:()=>import('../views/LayOut.vue'),
      children:[
        {
            path:'/index',
            name:'index',
            component:()=>import('../views/index/HomeIndex')
        },
        {
            path:'/orders/list',
            name:'orders_list',
            component:()=>import('../views/orders/OrdersList'),
            meta:{bread:['订单管理','订单列表']}
        },
        {
            path:'/waybill/list',
            name:'waybill_list',
            meta:{bread:['运单管理','运单列表'],keepAlive:true},
            component:()=>import('../views/waybill/WaybillList')
        },
        {
          path:'/waybill/list/detail',
          name:'waybill_list_detail',
          component:()=>import('@/views/waybill/WaybillDetail'),
          meta:{bread:['运单管理','运单列表','运单详情']}
        },
        {
          path:'/waybill/in',
          name:'waybill_entry',
          meta:{bread:['运单管理','运单录入']},
          component:()=>import('@/views/waybill/WaybillEntry')
        },
        {
          path:'/depart/data',
          name:'depart_list',
          component:()=>import('@/views/depart/DepartData'),
          meta:{bread:['发车管理','发车数据单']}
        },
        {
          path:'/carrier/list',
          name:'carrier_list',
          component:()=>import('@/views/carriers/CarriersList'),
          meta:{bread:['承运商管理','承运商列表']}
        },
        {
          path:'/carrier/drivers',
          name:'carrierdriver_list',
          component:()=>import('@/views/carriers/CarriersdriverList'),
          meta:{bread:['承运商管理','承运司机列表']}
        },
        {
          path:'/carrier/trucks',
          name:'carriervhicles_list',
          component:()=>import('@/views/carriers/VhiclesList'),
          meta:{bread:['承运商管理','车辆列表']}
        }
      ]
    },
    {
      path:'/login',
      name:'Login',
      component:()=>import('../views/LoginVue.vue')
    },
    
]